### ISSUE TITLE
Error in width and height

### ISSUE THREAD

**Issue by rassemdev** [smronju/vue-webcam#11]
I want to handle the width and height dynamically. so i did this:<vue-webcam ref='webcam' :width="imageWidth" :height="imageHeight"></vue-webcam>

but it is showing this error
[Vue warn]: Invalid prop: type check failed for prop "width". Expected Number, got String

**Comment by smronju** [comment]
You should provide number as it's value not string!

**Comment by rassemdev** [comment]
@smronju i did this:
` <vue-webcam ref='webcam' :width="widthstyle" :height="heightStyle"></vue-webcam>`
Im adding width and height dynamically, when the page load and taking the size of div and then adding it. suppose here widthstyle is = 700 and heightStyle is 500. still is showing error

**Comment by smronju** [comment]
Use number instead of 'widthstyle' e.g `<vue-webcam ref='webcam' :width="400" :height="400"></vue-webcam>`

**Comment by rassemdev** [comment]
i solved this--> this.heightStyle = parseInt(videoWidth)+"px";
