### ISSUE TITLE
Not Working in Vuejs2

### ISSUE THREAD

**Issue by caiooaugusto** [smronju/vue-webcam#3]
![image](https://cloud.githubusercontent.com/assets/4611524/26155685/700eda3e-3aea-11e7-9bc3-eb684f2dca69.png)

![image](https://cloud.githubusercontent.com/assets/4611524/26155704/7e2972e6-3aea-11e7-8dd5-5fa9a2c870ab.png)

![image](https://cloud.githubusercontent.com/assets/4611524/26155721/88321798-3aea-11e7-878b-0212b45da442.png)

**Comment by HugoOliveiraThor** [comment]
That is true in the new Version of vue he tells that the Vue.extend is not a function as the @caiooaugusto  says .

**Comment by HugoOliveiraThor** [comment]
I leave a pull request that fix the error .

**Comment by smronju** [comment]
Thanks for your contribution 👍
