### ISSUE TITLE
TypeError: Vue.extend is not a function

### ISSUE THREAD

**Issue by lucassmacedo** [smronju/vue-webcam#6]
Hello, i have this error.
TypeError: Vue.extend is not a function

**Comment by smronju** [comment]
May be you are missing something!

**Comment by zivkr2** [comment]
having the same issue

**Comment by yangjiedage** [comment]
me too. I have the same issue

**Comment by rataflo** [comment]
I think the minified version was not updated after the last fix.

**Comment by rvasoya** [comment]
i'm having the same problem...

**Comment by smronju** [comment]
Can anyone of you fix this please? I couldn't manage time to fix it.

**Comment by rvasoya** [comment]
i tried by registering it as file.vue insteaad of file.js and use it it my component file by importing template
i know it's not proper solution but i'm new in vue js 2.

**Comment by yipcma** [comment]
same issue here. not sure what's wrong with the Vue.extend used in the component

**Comment by brenohq** [comment]
same issue!

**Comment by sirb0rab0g1** [comment]
LOL THIS ERROR

**Comment by tylershyoon** [comment]
Can't use due to the same error...

**Comment by ymoreiratiti** [comment]
I solve this editing the 'node_modules\vue-webcam\VueWebcam.js'.

On line 6, change the `require('vue')` to `require('vue').default`

**Comment by kingRayhan** [comment]
### I'm also facing the same problem

![image](https://user-images.githubusercontent.com/7611746/35912748-ade96d56-0c27-11e8-9427-1752bbc7d6ef.png)


![image](https://user-images.githubusercontent.com/7611746/35912723-98c4c8f8-0c27-11e8-807e-721c0531e55b.png)

**Comment by hartonoda** [comment]
solved by doing const Vue = require('vue').default;

**Comment by kingRayhan** [comment]
close this issue 💩

**Comment by depie99** [comment]
> solved by doing const Vue = require('vue').default;

where to put it?

**Comment by jiangxiaoqiang** [comment]
same issue.

**Comment by lisbeth0720** [comment]
I have the same problem...

**Comment by asheroto** [comment]
Popular problem! I have it too!!!!!!!!!!
